/* =====================================================
   Fine Print Finance — Article data

   ├─ SWAPPING IMAGES ─────────────────────────────────
   │ Every image path on the site is defined in the IMAGES
   │ object below. To replace an image:
   │   1. Drop the new file into /assets/
   │   2. Update its path here
   │ If a file is missing, the site falls back to a labeled
   │ placeholder card so nothing breaks.
   └────────────────────────────────────────────
   ===================================================== */

const IMAGES = {
  // Full-screen hero on the home page. Recommend 2560×1440 (16:9),
  // dark left half for overlay text, character/visual on the right.
  hero:          '../assets/hero-image.png',

  // Portrait used in About + Ask-a-Pro + article author chips.
  // Recommend 800×1200 (2:3), face in upper third.
  josh:          '../assets/josh-portrait.png',

  // Article thumbnails — 16:9 video-style cover images.
  // Used on featured cards, article grid, and the article hero.
  // Add a `thumbnail` field on any article in ARTICLES to give it a cover.
  thumbnails: {
    moneyMissed:   '../assets/thumb-money-missed.png',
    taxStrategy:   '../assets/thumb-tax-strategy.png',
    irsRewards:    '../assets/thumb-irs-rewards.png',
    stopOverpay:   '../assets/thumb-stop-overpaying.png',
  },

  eventHeader:   '../assets/event-header-default.png',
};

const PILLARS = [
  { id: 'all',         label: 'All',         hue: 0 },
  { id: 'taxes',       label: 'Taxes',       hue: 145 },
  { id: 'investing',   label: 'Investing',   hue: 25 },
  { id: 'banking',     label: 'Banking',     hue: 200 },
  { id: 'healthcare',  label: 'Healthcare',  hue: 320 },
  { id: 'realestate',  label: 'Real Estate', hue: 38 },
  { id: 'cashflow',    label: 'Cash Flow',   hue: 350 },
];

const ARTICLES = [
  {
    slug: 'w2-deduction-1847',
    pillar: 'taxes',
    title: 'The $1,847 most W-2 filers leave on the table',
    excerpt: 'You took the standard deduction because TurboTax told you to. Here is how it quietly cost you the price of a used car.',
    date: 'Feb 12, 2026',
    readTime: '8 min read',
    author: 'Josh',
    video: 'EP. 53 — Watch on YouTube',
    bigNum: '$1,847',
    bgClass: 'hero-bg-taxes',
    thumbnail: IMAGES.thumbnails.moneyMissed,
    featured: 'lg', // 'lg' | 'sm' | null
    body: [
      { type:'lede', text:'Every April, the average W-2 filer who takes the standard deduction overpays the IRS by about $1,847. Not because the law is broken — because the menu is hidden.' },
      { type:'video', title:'Episode 53 — The $1,847 most filers miss', caption:'Watch the full episode (8 min). The article goes deeper on the math.' },
      { type:'p', text:'Here is what nobody tells you about the standard deduction: it is a default, not an answer. The IRS publishes the menu and waits for you to find it.' },
      { type:'h2', text:'What the standard deduction is actually doing' },
      { type:'p', text:'When you take the standard deduction, you are telling the IRS one thing — "I am not going to count what I spent this year, just give me the flat number." For most filers, that number is $14,600 in 2026.' },
      { type:'p', text:'The catch: there is a parallel menu called <strong>above-the-line deductions</strong> that you can take <em>in addition to</em> the standard deduction. The IRS does not advertise this. TurboTax shows it on a screen you skipped at 11:47pm on April 14th.' },
      { type:'stat', num:'$1,847', txt:'Average refund missed by W-2 filers who skip itemizable above-the-line deductions, per 2024 IRS data analyzed by ProPublica.' },
      { type:'h2', text:'The four lines that move the most money' },
      { type:'p', text:'In order of how much they actually return for an average filer in their 30s:' },
      { type:'image', alt:'Diagram: Schedule 1 lines 11-21 with the four highest-impact deductions highlighted', caption:'Schedule 1 is where the above-the-line deductions live. The four lines below move the most money for the average W-2 filer.' },
      { type:'list', items: [
        '<strong>Student loan interest</strong> — up to $2,500 deductible if your MAGI is under $90k single / $185k joint.',
        '<strong>HSA contributions</strong> — up to $4,150 single / $8,300 family, deductible whether you itemize or not.',
        '<strong>Traditional IRA contribution</strong> — $7,000 limit, deductible if you do not have a workplace retirement plan.',
        '<strong>Educator expenses</strong> — $300 if you are a K-12 teacher, no questions asked.',
      ]},
      { type:'h2', text:'Why your CPA might miss it anyway' },
      { type:'p', text:'CPAs charge by the form, not by the savings. Most W-2 returns are billed as a flat $300-500 because the CPA assumes a 1040 with a standard deduction and a W-2. If you have student loans and an HSA, those are separate worksheets. Most filers never mention them.' },
      { type:'fineprint', text:'§ "Above-the-line" means the deduction reduces your adjusted gross income (AGI) before the standard deduction is applied. This is different from itemized deductions, which replace the standard deduction. You can take above-the-line AND the standard deduction.' },
      { type:'h2', text:'The 10-minute fix' },
      { type:'p', text:'Pull up your 2025 return. Look at lines 11-21 of Schedule 1. If any of them are blank but you had student loans, an HSA, an IRA, or a classroom — you have a refund waiting. You have three years to amend.' },
      { type:'quote', text:'You are not bad with money. You were never shown the playbook.' },
    ],
    related: ['401k-094-fee', 'refund-not-windfall', 'hsa-triple-tax'],
  },
  {
    slug: '401k-094-fee',
    pillar: 'investing',
    title: 'The 0.94% fee eating a third of your 401(k)',
    excerpt: 'Industry-median 401(k) plan fees do not look like a lot on a statement. Compounded over 35 years, they take the price of a house.',
    date: 'Feb 5, 2026',
    readTime: '11 min read',
    author: 'Josh',
    video: 'EP. 51 — Watch on YouTube',
    bigNum: '0.94%',
    bgClass: 'hero-bg-investing',
    featured: 'sm',
    body: [
      { type:'lede', text:'A fee of less than 1% sounds invisible. The math is not.' },
      { type:'video', title:'Episode 51 — The 0.94% fee eating a third of your 401(k)', caption:'11-min episode. The fee math, with a calculator you can plug your own numbers into.' },
      { type:'p', text:'According to the Investment Company Institute, the median 401(k) plan in America charges participants 0.94% per year in total expenses — fund fees plus administrative fees plus the things plan administrators bury inside the prospectus.' },
      { type:'stat', num:'~33%', txt:'Portion of your final 401(k) balance that 1% in annual fees consumes over a 35-year career, per Vanguard fee-impact modeling.' },
      { type:'h2', text:'How a tiny number becomes a giant one' },
      { type:'p', text:'Compounding works on fees the same way it works on returns. A 1% fee does not just take 1% — it takes 1% of a base that would have otherwise grown. The longer you save, the worse it gets.' },
      { type:'image', alt:'Chart: $100k portfolio over 35 years at 0.04% vs 0.94% fee', caption:'Same starting balance. Same return. Different fee. $320k difference at year 35.' },
      { type:'p', text:'On a $100,000 portfolio held for 35 years at a 7% real return, a 0.04% fund fee leaves you with about $980,000. The same portfolio at a 0.94% fee leaves you with about $660,000. Same return. Same starting balance. Different fee. <strong>$320,000 difference.</strong>' },
      { type:'h2', text:'Where the fee actually lives' },
      { type:'list', items: [
        '<strong>Fund expense ratios</strong> — the most visible. Look for "Expense Ratio" or "ER" on each fund.',
        '<strong>Recordkeeping fees</strong> — flat monthly or per-account fees, often $40-100/yr.',
        '<strong>Administrative fees</strong> — usually a % of assets, deducted quarterly.',
        '<strong>Revenue sharing</strong> — funds pay the recordkeeper to be on the menu. You never see this directly.',
      ]},
      { type:'h2', text:'How to actually find your number' },
      { type:'p', text:'Log into your 401(k) provider. Look for a document called <strong>404(a)(5) Participant Fee Disclosure</strong>. By law, your plan has to give you one every year. It lists every fee in plain English.' },
      { type:'fineprint', text:'§ ERISA section 404(a)(5) requires plans to disclose fees in a standardized format. If your plan does not provide one, that is a Department of Labor violation — your HR department is required to produce it on request.' },
      { type:'h2', text:'What to do if your number is high' },
      { type:'p', text:'If your plan median is over 0.5%, your options in order of impact:' },
      { type:'list', items: [
        'Switch to the lowest-cost index fund in your menu — usually a target-date or S&P 500 fund.',
        'Contribute up to the match, then redirect new money to a <strong>traditional IRA</strong> where you control the fund menu.',
        'After leaving the employer, <strong>roll the balance</strong> to an IRA with low-fee funds.',
      ]},
    ],
    related: ['w2-deduction-1847', 'i-bonds-vs-hysa', 'hsa-triple-tax'],
  },
  {
    slug: 'free-checking-isnt',
    pillar: 'banking',
    title: 'Your "free" checking account is not free',
    excerpt: 'The bank pays you 0.01%. The Fed pays them 5.3%. That is not a service relationship — it is the deal.',
    date: 'Jan 28, 2026',
    readTime: '6 min read',
    author: 'Josh',
    video: 'EP. 49 — Watch on YouTube',
    bigNum: '5.3%',
    bgClass: 'hero-bg-banking',
    featured: 'sm',
    body: [
      { type:'lede', text:'There is no such thing as a free checking account. There is only a checking account where the fee is hidden in the spread.' },
      { type:'p', text:'When you deposit $10,000 into a "free" checking account, the bank loans it out at 7.5% (auto loans), 19% (credit cards), or invests it at 5.3% (the Fed pays them this overnight). They pay you 0.01%.' },
      { type:'stat', num:'$530/yr', txt:'Lost interest on a $10,000 checking balance when your bank pays 0.01% and a high-yield savings pays 5.3%.' },
      { type:'h2', text:'The three actual fees nobody calls fees' },
      { type:'list', items: [
        '<strong>The spread</strong> — what they earn on your deposit minus what they pay you. Annual cost on $10k: about $530.',
        '<strong>Overdraft "protection"</strong> — a $35 charge for a $4 cup of coffee. Effective APR: ~12,000%.',
        '<strong>Minimum balance fees</strong> — $12/mo if you dip below $1,500. $144/yr to keep money in an account that pays nothing.',
      ]},
      { type:'h2', text:'The two-account setup that fixes this' },
      { type:'p', text:'Keep one month of expenses in your free checking. Move everything else into a high-yield savings account (HYSA) at a separate institution. Link them. Sweep weekly.' },
      { type:'p', text:'You will spend 20 minutes setting it up and earn about $400-600 per year on a $10k balance. That is the fee you have been paying — back in your pocket.' },
      { type:'fineprint', text:'§ HYSA rates are variable and track the Federal Funds Rate. When the Fed cuts, HYSA rates fall. The math still works as long as the spread between your checking (0.01%) and your HYSA exists — which it always does.' },
    ],
    related: ['cash-back-card-cost', 'i-bonds-vs-hysa', 'w2-deduction-1847'],
  },
  {
    slug: 'hsa-triple-tax',
    pillar: 'healthcare',
    title: 'HSA: the only triple-tax-advantaged account nobody told you about',
    excerpt: 'Deductible going in. Grows tax-free. Comes out tax-free for medical. Nothing else in the tax code does this.',
    date: 'Jan 21, 2026',
    readTime: '9 min read',
    author: 'Josh',
    video: 'EP. 47 — Watch on YouTube',
    bigNum: '3×',
    bgClass: 'hero-bg-healthcare',
    featured: null,
    body: [
      { type:'lede', text:'There is exactly one account in the entire U.S. tax code that gives you a tax break on the way in, on the growth, and on the way out. It is not the 401(k). It is not the Roth IRA. It is the HSA.' },
      { type:'p', text:'The catch — and the reason nobody talks about it — is that you can only contribute to one if you have a high-deductible health plan. Most people see "high deductible" and run. The math says you should not.' },
      { type:'h2', text:'The three tax advantages, in plain English' },
      { type:'list', items: [
        '<strong>Contributions are tax-deductible</strong> — like a traditional IRA, but better, because they also escape FICA if you contribute through payroll.',
        '<strong>Growth is tax-free</strong> — like a Roth IRA. Buy index funds inside the HSA and they compound untouched.',
        '<strong>Withdrawals are tax-free for qualified medical expenses</strong> — and after 65, you can withdraw for anything at ordinary income rates, just like a traditional IRA.',
      ]},
      { type:'stat', num:'$8,300', txt:'2026 family contribution limit. Single limit is $4,150. Add $1,000 if you are 55+.' },
      { type:'h2', text:'The move most people miss' },
      { type:'p', text:'Do not spend your HSA. Pay medical bills out of pocket. Save the receipts. Let the HSA invest. Decades later, reimburse yourself tax-free for those old receipts.' },
      { type:'p', text:'You get the deduction now, the growth for 30 years, and tax-free reimbursement whenever you want it. Nothing else in the code lets you do this.' },
      { type:'fineprint', text:'§ "Qualified medical expense" is broader than people think. It covers most dental, vision, prescription, therapy, and many over-the-counter items per IRS Publication 502. Save receipts in a folder labeled by year.' },
    ],
    related: ['w2-deduction-1847', '401k-094-fee', 'refund-not-windfall'],
  },
  {
    slug: 'closing-costs-6-fees',
    pillar: 'realestate',
    title: 'Closing costs: where 6 hidden fees live (and which ones to fight)',
    excerpt: 'On a $400k house, closing costs run $12,000-$20,000. About a third is genuinely negotiable. Most buyers never ask.',
    date: 'Jan 14, 2026',
    readTime: '12 min read',
    author: 'Josh',
    video: 'EP. 45 — Watch on YouTube',
    bigNum: '$5,200',
    bgClass: 'hero-bg-realestate',
    featured: null,
    body: [
      { type:'lede', text:'Closing day is the worst day to negotiate. Which is exactly why every fee on the disclosure expects you not to.' },
      { type:'p', text:'On the average $400,000 home purchase, you will pay between $12,000 and $20,000 in closing costs. About $5,200 of that is negotiable — if you know which line items to push back on, and when.' },
      { type:'h2', text:'The 6 line items, ranked by how movable they are' },
      { type:'list', items: [
        '<strong>Origination fee</strong> (~$2,000) — fully negotiable, especially if you have multiple loan offers.',
        '<strong>Title insurance</strong> (~$1,500) — you can shop this independently of the lender.',
        '<strong>Underwriting fee</strong> (~$800) — often waivable for relationship customers.',
        '<strong>Discount points</strong> (~$1,000 each) — only buy if you will hold the loan past the break-even period.',
        '<strong>Recording fees</strong> (~$200) — fixed by the county, not negotiable.',
        '<strong>Transfer taxes</strong> (~$2,000) — set by state/local law, not negotiable.',
      ]},
      { type:'stat', num:'$5,200', txt:'Average negotiable amount on a $400k home purchase, per LendingTree 2025 closing-cost survey.' },
      { type:'h2', text:'The script that gets it done' },
      { type:'p', text:'When you get your Loan Estimate, you have three days. Email your lender:' },
      { type:'quote', text:'"I have offers from [Lender B] and [Lender C]. Their origination is $X and they are waiving the underwriting fee. Can you match before I commit?"' },
      { type:'p', text:'Lenders expect this conversation. They have approval to drop these fees up to a defined limit. They will not volunteer the drop — you have to ask.' },
      { type:'fineprint', text:'§ The Loan Estimate is a federally standardized form (TRID rules). Section A is origination charges — that is your battlefield. Section B is services you cannot shop for. Section C is services you can shop for (title, attorney). The big-three fees to push: origination, underwriting, title.' },
    ],
    related: ['401k-094-fee', 'free-checking-isnt', 'hsa-triple-tax'],
  },
  {
    slug: 'i-bonds-vs-hysa',
    pillar: 'investing',
    title: 'I-Bonds vs. high-yield savings: the real math',
    excerpt: 'When inflation is high, I-Bonds win. When the Fed is hiking, HYSA wins. Here is the framework, not the hype.',
    date: 'Jan 7, 2026',
    readTime: '7 min read',
    author: 'Josh',
    video: 'EP. 43 — Watch on YouTube',
    bigNum: '4.4%',
    bgClass: 'hero-bg-investing',
    featured: null,
    body: [
      { type:'lede', text:'The "what should I do with my emergency fund" question has a real answer, and it depends on exactly two variables: the current I-Bond composite rate, and the current HYSA rate.' },
      { type:'h2', text:'The 30-second framework' },
      { type:'list', items: [
        '<strong>Need it in under 12 months?</strong> HYSA. I-Bonds have a 1-year lockup.',
        '<strong>Need it in 1-5 years and inflation is &gt;3%?</strong> I-Bond, accept the 3-month interest penalty if you cash early.',
        '<strong>Need it in 1-5 years and inflation is &lt;3%?</strong> HYSA. The Fed-driven rate beats the inflation-driven rate.',
      ]},
      { type:'stat', num:'$10,000', txt:'Annual I-Bond purchase limit per person per year. Spouse + tax refund redirect can stretch this to $25,000.' },
      { type:'p', text:'I-Bonds are the only investment in the U.S. system that pays a rate guaranteed to match inflation. That is structurally different from an HYSA, which pays whatever the Fed sets. When inflation outpaces Fed policy (2021-2022), I-Bonds crush. When the Fed gets ahead of inflation (2023-2024), HYSA crushes.' },
      { type:'fineprint', text:'§ Buy at TreasuryDirect.gov. The site looks like it was designed in 1998 because it was. The interest is taxed federally but not at the state level — small bonus for high-tax-state residents.' },
    ],
    related: ['401k-094-fee', 'free-checking-isnt', 'hsa-triple-tax'],
  },
  {
    slug: 'refund-not-windfall',
    pillar: 'taxes',
    title: 'Your refund is not a windfall — it is an interest-free loan to the IRS',
    excerpt: 'If you got a $3,000 refund last April, you let the government hold $250 of your money every month for nothing. There is a fix.',
    date: 'Dec 30, 2025',
    readTime: '5 min read',
    author: 'Josh',
    video: 'EP. 41 — Watch on YouTube',
    bigNum: '$250',
    bgClass: 'hero-bg-taxes',
    thumbnail: IMAGES.thumbnails.stopOverpay,
    featured: null,
    body: [
      { type:'lede', text:'A tax refund means one thing: you overpaid. The IRS held your money for a year and gave it back without interest. That is not a gift — that is a loan you accidentally made.' },
      { type:'p', text:'The average federal refund last year was $3,138. That is $261 a month the average filer could have had in an HYSA earning 5%. Total cost of the "windfall": about $86 in foregone interest.' },
      { type:'stat', num:'$3,138', txt:'Average federal tax refund, 2024 IRS data. The bigger your refund, the more you overpaid.' },
      { type:'h2', text:'The W-4 fix, in plain English' },
      { type:'p', text:'Open your W-4 form. The newer version has a worksheet — Step 4(b) is where you increase your "Other Deductions" to reduce withholding. Plug your numbers into the IRS Tax Withholding Estimator, then send the updated W-4 to HR.' },
      { type:'p', text:'You will get a smaller refund (or owe a little) — and you will get the rest of the money every paycheck instead of every April.' },
      { type:'fineprint', text:'§ The IRS does not charge underpayment penalties as long as you have paid in at least 100% of last year\'s liability (110% if you earn over $150k), OR 90% of this year\'s. Aim to land inside that "safe harbor" band — that is the lowest refund without triggering a penalty.' },
    ],
    related: ['w2-deduction-1847', '401k-094-fee', 'free-checking-isnt'],
  },
  {
    slug: 'build-tax-strategy-first',
    pillar: 'taxes',
    title: 'Build your tax strategy — what to do first',
    excerpt: 'Tax strategy isn\'t about secrets. It\'s about doing the obvious things in the right order — and most people never get past step one.',
    date: 'Feb 26, 2026',
    readTime: '10 min read',
    author: 'Josh',
    video: 'EP. 56 — Watch on YouTube',
    bigNum: 'STEP 1',
    bgClass: 'hero-bg-taxes',
    thumbnail: IMAGES.thumbnails.taxStrategy,
    featured: 'sm',
    body: [
      { type:'lede', text:'Most "tax strategy" content sells you the answer to step seven. The problem is, almost nobody has done steps one through six yet — and steps one through six are where the actual money is.' },
      { type:'video', title:'Episode 56 — Build your tax strategy', caption:'10 min — the order of operations from a $0 tax bill back to where you are now.' },
      { type:'p', text:'Here is the order of operations, in plain English. Do these in sequence. Each step assumes the one before it is complete.' },
      { type:'h2', text:'Step 1 — Max your tax-advantaged accounts' },
      { type:'p', text:'Before you talk about strategy, you have to use the boxes the IRS already built for you. 401(k) up to the match, then HSA if you have a high-deductible plan, then Roth IRA. These three accounts cover most of what most W-2 filers ever need.' },
      { type:'h2', text:'Step 2 — Pick the right deduction path' },
      { type:'p', text:'Standard deduction vs. itemized is a math question, not a values question. Add up your mortgage interest, state and local taxes (capped at $10k), and charitable giving. If that number beats the standard deduction ($14,600 single / $29,200 joint), you itemize. If not, you don\'t.' },
      { type:'h2', text:'Step 3 — Above-the-line deductions, no matter what' },
      { type:'p', text:'These work whether you itemize or not. Student loan interest, HSA contributions, traditional IRA, educator expenses. This is the section that nets the average W-2 filer about $1,847 they\'re leaving on the table.' },
      { type:'stat', num:'$1,847', txt:'Average money missed when filers skip Schedule 1 above-the-line deductions, per the 2024 IRS data.' },
      { type:'h2', text:'Step 4 — Now we can talk strategy' },
      { type:'p', text:'Once 1–3 are done: Roth conversions in low-income years, real estate depreciation, tax-loss harvesting, donor-advised funds. These are real moves — but only if the boring stuff is finished first.' },
      { type:'fineprint', text:'§ Tax strategy without the basics is like buying a Lamborghini before you have a driver\'s license. The exotic moves get attention, but the boring four steps above account for ~90% of what most filers will ever save.' },
    ],
    related: ['w2-deduction-1847', 'irs-7-rewards', 'hsa-triple-tax'],
  },
  {
    slug: 'irs-7-rewards',
    pillar: 'taxes',
    title: '7 IRS rewards hidden in plain sight',
    excerpt: 'The IRS isn\'t just a collector — it\'s a list of seven incentives the government wants you to take. Most people use one or two.',
    date: 'Feb 19, 2026',
    readTime: '9 min read',
    author: 'Josh',
    video: 'EP. 55 — Watch on YouTube',
    bigNum: '7',
    bgClass: 'hero-bg-taxes',
    thumbnail: IMAGES.thumbnails.irsRewards,
    featured: 'sm',
    body: [
      { type:'lede', text:'The tax code looks like a punishment. It reads like one too. But buried in it is a list of seven things the federal government will literally pay you to do — if you\'re willing to fill out the form.' },
      { type:'video', title:'Episode 55 — 7 IRS rewards hidden in plain sight', caption:'9-min walkthrough of each category, with the form numbers.' },
      { type:'p', text:'The IRS doesn\'t advertise these. They are not "loopholes" — they are explicit policy. Each one exists because Congress decided to subsidize a specific behavior.' },
      { type:'h2', text:'1. Housing' },
      { type:'p', text:'The mortgage interest deduction, the SALT deduction up to $10k, and the $250k/$500k capital gains exclusion when you sell your primary home. If you own, you should know all three numbers.' },
      { type:'h2', text:'2. Energy' },
      { type:'p', text:'Residential clean-energy credit (30% of installation cost for solar, wind, geothermal). EV tax credit ($7,500 new, $4,000 used). Energy-efficient home improvement credit ($1,200/yr for windows, doors, insulation).' },
      { type:'h2', text:'3. Retirement' },
      { type:'p', text:'Traditional 401(k) and IRA contributions reduce your taxable income now. Roth versions are tax-free later. Saver\'s credit gives low-to-mid income earners up to $1,000 back just for contributing.' },
      { type:'h2', text:'4. Healthcare' },
      { type:'p', text:'HSA is the triple-tax-advantaged king. Premium tax credit subsidizes ACA marketplace plans. Medical expense deduction once costs exceed 7.5% of AGI.' },
      { type:'h2', text:'5. Education' },
      { type:'p', text:'American Opportunity Credit ($2,500/yr per student, first four years). Lifetime Learning Credit ($2,000/yr). Student loan interest deduction ($2,500/yr). 529 plans for tax-free growth on education savings.' },
      { type:'h2', text:'6. Charity' },
      { type:'p', text:'Cash and goods donations to qualified nonprofits, deductible if you itemize. Donor-advised funds let you front-load multiple years of giving into one big deduction.' },
      { type:'h2', text:'7. Small business' },
      { type:'p', text:'QBI deduction (up to 20% off qualified business income). Section 179 expensing on equipment. Self-employed retirement accounts with much higher limits than W-2 versions.' },
      { type:'stat', num:'~$4,800', txt:'Average annual value to a middle-income household that fully uses just three of these seven categories.' },
      { type:'fineprint', text:'§ Every one of these has eligibility rules and income phase-outs. The point of this list isn\'t to claim everything — it\'s to know which ones apply to you so they\'re not invisible.' },
    ],
    related: ['build-tax-strategy-first', 'w2-deduction-1847', 'hsa-triple-tax'],
  },
  {
    slug: 'cash-back-card-cost',
    pillar: 'banking',
    title: 'The "cash back" card that actually costs you money',
    excerpt: '2% cash back on a card with a 23% APR is not a deal. It is a marketing line that depends on you not paying off the balance.',
    date: 'Dec 23, 2025',
    readTime: '10 min read',
    author: 'Josh',
    video: 'EP. 39 — Watch on YouTube',
    bigNum: '23%',
    bgClass: 'hero-bg-banking',
    featured: null,
    body: [
      { type:'lede', text:'Cash back cards earn the bank more than they pay you. The math only works in your favor if you pay the balance in full, every month, forever. That is a narrow lane.' },
      { type:'p', text:'The average cardholder carries a $6,300 balance at 23% APR. The same card pays 2% cash back. Net annual cost: about $1,200 in interest minus $300 in rewards = <strong>$900 loss.</strong>' },
      { type:'stat', num:'-$900', txt:'Average annual net cost of a 2% cash-back card for a cardholder carrying the median revolving balance.' },
      { type:'h2', text:'When cash back actually works' },
      { type:'list', items: [
        'You pay the statement balance in full every month — no exceptions.',
        'You do not chase categories or sign-up bonuses that change your behavior.',
        'You treat the card like a debit card with a 30-day delay.',
      ]},
      { type:'p', text:'Used that way, a 2% card on $30k of annual spend returns $600/yr free. That is the deal. Anything else is a fee with extra steps.' },
      { type:'fineprint', text:'§ Credit card APR is determined daily, applied to the average daily balance. There is no grace period on a balance that carries from one cycle to the next — interest accrues from purchase date, not statement date. The "21 day grace period" only applies when you paid the previous statement in full.' },
    ],
    related: ['free-checking-isnt', 'i-bonds-vs-hysa', 'refund-not-windfall'],
  },
];

const EVENTS = [
  {
    slug: 'tax-strategy-workshop-mar26',
    title: 'The $1,847 Tax Workshop',
    tagline: 'A live walkthrough of Schedule 1 — line by line. Bring your 2025 return.',
    status: 'upcoming',
    category: 'Live workshop',
    startDate: 'Saturday, March 14, 2026',
    endDate: '',
    startTime: '10:00 AM',
    endTime: '12:00 PM',
    timezone: 'EST',
    format: 'Online · Live Stream',
    venue: 'Zoom (link emailed after registration)',
    city: '',
    region: 'Online',
    thumbnail: IMAGES.eventHeader,
    thumbnailLabel: 'Event hero · tax-workshop',
    seatsTotal: 500,
    seatsLeft: 87,
    description: [
      'Two hours, one screen, every line that actually moves the needle on a W-2 return. We open Schedule 1 of the 1040, walk down the page, and stop on every line where most filers leave money behind.',
      'If you took the standard deduction last April, this workshop is for you. By the end, you\'ll have a checklist of every above-the-line deduction you might qualify for and the exact form numbers to claim them.',
    ],
    schedule: [
      { time:'10:00 AM', title:'Welcome + the standard-deduction trap', desc:'Why the default answer is wrong for most W-2 filers.' },
      { time:'10:15 AM', title:'Schedule 1, lines 11-21 — the menu', desc:'Walking the page, line by line.' },
      { time:'11:00 AM', title:'The four biggest movers', desc:'Student loans, HSA, IRA, educator. Live worksheet.' },
      { time:'11:30 AM', title:'Live Q&A', desc:'Bring your numbers. We answer in order.' },
      { time:'11:55 AM', title:'Wrap + send the playbook', desc:'PDF emailed to attendees within an hour.' },
    ],
    speakers: [
      { name:'Josh', role:'Host · Fine Print Finance', image:'../assets/josh-portrait.png' },
      { name:'Maria Chen, CPA', role:'Guest expert · 14 yrs IRS practice', image:'' },
    ],
    tickets: [
      { id:'free', label:'Free livestream', price:0, desc:'Watch live + audience Q&A access' },
      { id:'recording', label:'Recording + playbook PDF', price:19, desc:'Get the recording, slides, and tax checklist' },
      { id:'vip', label:'VIP review', price:97, desc:'Everything above + a 20-min 1:1 with Maria to review your return' },
    ],
    faqs: [
      { q:'Do I need any tax background?', a:'No. We start at zero. If you\'ve filed a return before — even with TurboTax — you\'ll be able to follow.' },
      { q:'Will there be a recording?', a:'Only for paid tickets. Free livestream attendees get to watch live; the recording is reserved for the $19 tier.' },
      { q:'What\'s the refund policy?', a:'Full refund within 7 days of purchase, no questions asked. After the event, refunds are case-by-case.' },
    ],
  },
  {
    slug: 'live-qa-401k-fees',
    title: '401(k) Fee Audit · Live Q&A',
    tagline: 'Pull up your plan\'s 404(a)(5) disclosure. We\'ll read it together.',
    status: 'upcoming',
    category: 'Live Q&A',
    startDate: 'Wednesday, March 26, 2026',
    endDate: '',
    startTime: '8:00 PM',
    endTime: '9:00 PM',
    timezone: 'EST',
    format: 'Online · Live Stream',
    venue: 'YouTube Live',
    city: '',
    region: 'Online',
    thumbnail: IMAGES.eventHeader,
    thumbnailLabel: 'Event hero · 401k-qa',
    seatsTotal: 0,
    seatsLeft: 0,
    description: [
      'Bring your 401(k) plan\'s annual fee disclosure (the 404(a)(5) document HR is required to give you every year). We read it live, on screen, anonymized. You leave knowing your real all-in fee number — and what to do if it\'s over 0.5%.',
      'Free. Anonymous. Ninety minutes. If you\'ve been wondering whether your plan is quietly costing you a third of your retirement, this is where you find out.',
    ],
    schedule: [
      { time:'8:00 PM', title:'How to find your 404(a)(5)', desc:'Where it lives in your plan portal, in one click.' },
      { time:'8:10 PM', title:'How to read the four sections', desc:'Investment fees, plan admin fees, individual service fees, total.' },
      { time:'8:30 PM', title:'Anonymous live audits', desc:'Submit your fee number in chat. We rank them live and call out the worst ones.' },
      { time:'8:50 PM', title:'What to do about a high fee', desc:'Three options in order of impact.' },
    ],
    speakers: [
      { name:'Josh', role:'Host · Fine Print Finance', image:'../assets/josh-portrait.png' },
    ],
    tickets: [
      { id:'free', label:'Free · RSVP for reminder', price:0, desc:'We\'ll email you a reminder + the slides after.' },
    ],
    faqs: [
      { q:'Will my plan info be shown publicly?', a:'No. We only ask for your total fee % — no plan name, no employer, no balance. The chat is anonymous.' },
      { q:'What if I can\'t find my 404(a)(5)?', a:'Show up anyway. The first ten minutes covers exactly where to find it on every major platform (Fidelity, Vanguard, Empower, Principal, etc.).' },
    ],
  },
  {
    slug: 'real-estate-closing-bootcamp',
    title: 'Closing Costs Bootcamp · 4-week cohort',
    tagline: 'A small-group workshop for buyers under contract or about to be. Pre-closing prep, live walkthroughs.',
    status: 'upcoming',
    category: '4-week cohort',
    startDate: 'Tuesdays, April 7 – April 28, 2026',
    endDate: '',
    startTime: '7:00 PM',
    endTime: '8:30 PM',
    timezone: 'EST',
    format: 'Cohort · Zoom + Discord',
    venue: 'Zoom (live) + Discord (between sessions)',
    city: '',
    region: 'Online',
    thumbnail: IMAGES.eventHeader,
    thumbnailLabel: 'Event hero · closing-cohort',
    seatsTotal: 30,
    seatsLeft: 9,
    description: [
      'A small-group bootcamp for buyers actively under contract or expecting to be in the next 60 days. Four weekly live sessions covering the closing process from Loan Estimate through Closing Disclosure — with negotiation scripts you actually use.',
      'Cohort capped at 30 so we can review your real numbers. Past graduates saved an average of $3,400 in negotiable fees on their close.',
    ],
    schedule: [
      { time:'Week 1', title:'The Loan Estimate, decoded', desc:'Section A, B, C — what\'s movable, what\'s fixed.' },
      { time:'Week 2', title:'The shopping play', desc:'Title insurance, attorney fees, points. Live shopping demo.' },
      { time:'Week 3', title:'Negotiation scripts', desc:'The exact emails that drop origination and underwriting fees.' },
      { time:'Week 4', title:'Closing Disclosure review', desc:'Bring yours. We red-line it together.' },
    ],
    speakers: [
      { name:'Josh', role:'Host · Fine Print Finance', image:'../assets/josh-portrait.png' },
      { name:'David Park', role:'Guest · 12yr mortgage broker, recovering', image:'' },
    ],
    tickets: [
      { id:'cohort', label:'Full 4-week cohort', price:297, desc:'Live sessions + Discord + Closing Disclosure review' },
      { id:'partner', label:'Cohort + partner seat', price:397, desc:'Bring a co-buyer (spouse/partner) at one shared rate' },
    ],
    faqs: [
      { q:'What if I\'m not under contract yet?', a:'Still useful — we cover the Loan Estimate stage which is BEFORE you sign. If you\'re more than 90 days out, the live Q&A might run before your timeline.' },
      { q:'Are sessions recorded?', a:'Yes, all four sessions are recorded for cohort members. The Discord stays open for 6 months after the cohort ends.' },
      { q:'Refund policy?', a:'Full refund before Week 1 starts. After Week 1, refunds are pro-rated.' },
    ],
  },
  {
    slug: 'past-hsa-deep-dive',
    title: 'HSA Deep Dive — Past Event',
    tagline: 'How to use the only triple-tax-advantaged account. 90-min workshop.',
    status: 'past',
    category: 'Workshop · Past',
    startDate: 'Saturday, February 8, 2026',
    endDate: '',
    startTime: '11:00 AM',
    endTime: '12:30 PM',
    timezone: 'EST',
    format: 'Online · Recorded',
    venue: 'Recording available to members',
    city: '',
    region: 'Online',
    thumbnail: IMAGES.eventHeader,
    thumbnailLabel: 'Event hero · hsa-past',
    seatsTotal: 0,
    seatsLeft: 0,
    description: [
      'A 90-minute workshop on how to actually use the HSA — including the receipt-saving strategy that nobody talks about. Recording available to community members.',
    ],
    schedule: [
      { time:'00:00', title:'The three tax advantages', desc:'In plain English.' },
      { time:'15:00', title:'The receipt strategy', desc:'Pay out of pocket, invest the HSA, reimburse later.' },
      { time:'45:00', title:'Investment menu walkthrough', desc:'How to find low-fee funds inside your HSA provider.' },
      { time:'70:00', title:'Live Q&A', desc:'Edge cases, ineligible expenses, what counts.' },
    ],
    speakers: [
      { name:'Josh', role:'Host · Fine Print Finance', image:'../assets/josh-portrait.png' },
    ],
    tickets: [
      { id:'member', label:'Members · Watch recording', price:0, desc:'Free for community members. Non-members can join the community for $9/mo.' },
    ],
    faqs: [
      { q:'Can I watch this without joining the community?', a:'Not currently. The recording is a member perk. Join for $9/mo (first 14 days free) and you get access to this plus future recordings.' },
    ],
  },
];

const COMMUNITY_THREADS = [
  { initials:'MR', name:'Maria R.', topic:'Anyone amend a return 2 years back for missed HSA deduction?', replies:14 },
  { initials:'DK', name:'Devin K.', topic:'Got my plan’s 404(a)(5) — fees are 1.4%. What now?', replies:23 },
  { initials:'AT', name:'Alex T.', topic:'Closing in 3 weeks. Lender just dropped underwriting fee after I asked. Holy.', replies:9 },
  { initials:'JL', name:'Jenny L.', topic:'I-Bonds vs HYSA for a 2027 down payment — what would you do?', replies:31 },
];

Object.assign(window, { IMAGES, PILLARS, ARTICLES, COMMUNITY_THREADS, EVENTS });
